# This file was generated by GoReleaser. DO NOT EDIT.
cask "ddt" do
  name "ddt"
  desc "Docker development tools CLI"
  homepage "https://github.com/antimatter-studios/docker-dev-tools"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ddt"

  on_macos do
    on_intel do
      url "https://github.com/antimatter-studios/docker-dev-tools/releases/download/v#{version}/ddt_#{version}_darwin_amd64.tar.gz"
      sha256 "b2293be8e6f972fbe35a109fc70babe7aef746b0adc091586cd2e37791e727e2"
    end
    on_arm do
      url "https://github.com/antimatter-studios/docker-dev-tools/releases/download/v#{version}/ddt_#{version}_darwin_arm64.tar.gz"
      sha256 "26ce5adf5a174a7d5ce0bd2804076258d7d9a651cd2ff839278e0bc9a5c415aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antimatter-studios/docker-dev-tools/releases/download/v#{version}/ddt_#{version}_linux_amd64.tar.gz"
      sha256 "1f3f25be08515a1c2777b4ad423e9de53550bd8f9975dda3efb5a551b5c257fa"
    end
    on_arm do
      url "https://github.com/antimatter-studios/docker-dev-tools/releases/download/v#{version}/ddt_#{version}_linux_arm64.tar.gz"
      sha256 "c4cd4cd2e454f1d6fa5287dfc1879846e3793565e3f9d863079bbeccb64b7c63"
    end
  end

  # No zap stanza required
end
