# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotman" do
  name "dotman"
  desc "Git-backed dotfile workflow manager"
  homepage "https://github.com/christhomas/dotman"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotman"

  on_macos do
    on_intel do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_darwin_amd64.tar.gz"
      sha256 "a45f6c7e7db6b4a6e66960617be020f889d043d5c0dd3a1900d1e764e9342c3c"
    end
    on_arm do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_darwin_arm64.tar.gz"
      sha256 "4e02010440c1b3e6b927fa25bc50064d41f9da127a38ff041ccc8de0f98ffc64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_linux_amd64.tar.gz"
      sha256 "d6ffb3736622466cadce92d66e588ea1f493fbbd1d695a138ddfe2013b5134f4"
    end
    on_arm do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_linux_arm64.tar.gz"
      sha256 "ac63c4cf2b42573c13821ba9061d2a4f0b9b180ba0a3a0b87a10756cccdf08bf"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotman"]
  end

  # No zap stanza required
end
