# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotman" do
  name "dotman"
  desc "Git-backed dotfile workflow manager"
  homepage "https://github.com/christhomas/dotman"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotman"

  on_macos do
    on_intel do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_darwin_amd64.tar.gz"
      sha256 "1d8146ff4305da8aa56b66afd5814e3c92e8085589aacb319479211b05517544"
    end
    on_arm do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_darwin_arm64.tar.gz"
      sha256 "a77ecb23762bbac25df001dccf3e22a2384faa0965e5190e95f423fe7adaa1fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_linux_amd64.tar.gz"
      sha256 "fc6a0332503174b35271e296ad783b374c658b25e628ffb82b6c887cb91724c3"
    end
    on_arm do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_linux_arm64.tar.gz"
      sha256 "c11edb072131c8af9db7a26c3be23408b6101add3f9c5bd49e730dcfc8abf644"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotman"]
  end

  # No zap stanza required
end
