# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotman" do
  name "dotman"
  desc "Git-backed dotfile workflow manager"
  homepage "https://github.com/christhomas/dotman"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotman"

  on_macos do
    on_intel do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_darwin_amd64.tar.gz"
      sha256 "f8a8af24692c29646eb1244c216511e54d0ce45d0bb4aaa8d9c04acca38d4577"
    end
    on_arm do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_darwin_arm64.tar.gz"
      sha256 "295e18334035016e1a9268256edbc3220a730b72e8b0d2b719e8fc29d6f6a79e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_linux_amd64.tar.gz"
      sha256 "a873ffcbb4e44689f2d36bb4b74f6d89a234d8b1c8b6a157bf652a9d53a2a672"
    end
    on_arm do
      url "https://github.com/christhomas/dotman/releases/download/v#{version}/dotman_#{version}_linux_arm64.tar.gz"
      sha256 "2659d3b339e2d1b669becb4e44d54347003f5564fe52c12e9e074a9edcc9ed83"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotman"]
  end

  # No zap stanza required
end
