# This file was generated by GoReleaser. DO NOT EDIT.
cask "tacli" do
  name "tacli"
  desc "Team Agentica CLI — inspect and manage the platform"
  homepage "https://github.com/antimatter-studios/teamagentica"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tacli"

  on_macos do
    on_intel do
      url "https://github.com/antimatter-studios/teamagentica/releases/download/v#{version}/tacli_#{version}_darwin_amd64.tar.gz"
      sha256 "44d9355ca21250e2ed54518a5e10e1d7d3476c97b0993fa57875613405961c63"
    end
    on_arm do
      url "https://github.com/antimatter-studios/teamagentica/releases/download/v#{version}/tacli_#{version}_darwin_arm64.tar.gz"
      sha256 "06ae16dc2ffc733be96143ffa73635ce8775b97b5e2a71d2180dfd7b2050a1e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antimatter-studios/teamagentica/releases/download/v#{version}/tacli_#{version}_linux_amd64.tar.gz"
      sha256 "10dccfdf4e7125d6cf4e22f863e90d02adaa78e5f9fb9dce5e031a6f2cfe9af1"
    end
    on_arm do
      url "https://github.com/antimatter-studios/teamagentica/releases/download/v#{version}/tacli_#{version}_linux_arm64.tar.gz"
      sha256 "1cc6cd0e8d91136e9f1fab6c27c66abb117687697cfb9853ebac98882fb0a535"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tacli"]
  end

  # No zap stanza required
end
