# This file was generated by GoReleaser. DO NOT EDIT.
cask "tacli" do
  name "tacli"
  desc "Team Agentica CLI — inspect and manage the platform"
  homepage "https://github.com/antimatter-studios/teamagentica"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tacli"

  on_macos do
    on_intel do
      url "https://github.com/antimatter-studios/teamagentica/releases/download/v#{version}/tacli_#{version}_darwin_amd64.tar.gz"
      sha256 "d28a90fa405fbde69522d7b241104e7ef05fb00162e0b47338074dc7c89e6684"
    end
    on_arm do
      url "https://github.com/antimatter-studios/teamagentica/releases/download/v#{version}/tacli_#{version}_darwin_arm64.tar.gz"
      sha256 "cebebfdc5c7979ef971b4aa02a19cb7306ffc545d36d0d2791b215be99805e77"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antimatter-studios/teamagentica/releases/download/v#{version}/tacli_#{version}_linux_amd64.tar.gz"
      sha256 "033bb075212e60ce26d5a0df2ec41eb8bc979f072999611c1663d0967adb6ec6"
    end
    on_arm do
      url "https://github.com/antimatter-studios/teamagentica/releases/download/v#{version}/tacli_#{version}_linux_arm64.tar.gz"
      sha256 "4e6f0dd98cbac407ed2d02b801de2045b420694040847bc26cba7edd634e2f32"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tacli"]
  end

  # No zap stanza required
end
