# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Instantmailcheck < Formula
  desc "Diagnose any mail server in seconds — DNS, SMTP, IMAP, POP3, TLS, DKIM/SPF/DMARC, MTA-STS"
  homepage "https://github.com/rest-mail/instantmailcheck"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-mail/instantmailcheck/releases/download/v0.1.0/instantmailcheck_0.1.0_darwin_amd64.tar.gz"
      sha256 "751100c53eccae4c028ef1a8df3d5a2e8001e453540d69f6115b16bf7a03ac31"

      define_method(:install) do
        bin.install "instantmailcheck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-mail/instantmailcheck/releases/download/v0.1.0/instantmailcheck_0.1.0_darwin_arm64.tar.gz"
      sha256 "5d65ae99b16e7ee448862afb395bdddad9cf26185e3d8b6b5ac68bc39be63e18"

      define_method(:install) do
        bin.install "instantmailcheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-mail/instantmailcheck/releases/download/v0.1.0/instantmailcheck_0.1.0_linux_amd64.tar.gz"
      sha256 "f12d2ebb49b6de31ae2fda88afd027e8fda13a1ef1d4aa31d64f503967b2259c"
      define_method(:install) do
        bin.install "instantmailcheck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-mail/instantmailcheck/releases/download/v0.1.0/instantmailcheck_0.1.0_linux_arm64.tar.gz"
      sha256 "c9dac8a02dd6c97df5289f2be163d8b2c6647e0b4fb006d5f6599fadb25fac29"
      define_method(:install) do
        bin.install "instantmailcheck"
      end
    end
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/instantmailcheck --version")
  end
end
